### ISSUE TITLE
Creating animation file and background for level_select and adding it in as a function

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#116]
Comment below any suggestions; (here's my take)
- list of level_names need to be created as well as their order needs to be listed below (world 1 - level 1)
- background of the level_select
- vid/gif of the player doing the jump animation to the next platform when the player hits a creation key

more to come...

**Comment by slysnivy** [comment]
Refer to dsn_levels v.0.2.5, which I believe contains the animations using pygame

**Comment by slysnivy** [comment]
Let me know what you think 👍

**Comment by slysnivy** [comment]
I think we can close this comment as you said you were fine with it.
