### ISSUE TITLE
levels.txt Text naming

### ISSUE THREAD

**Issue by slysnivy** [shoc71/dont-stop-now#117]
Could we have it be either one or three lines consistently (as right now there are both, I want one formatting style only). Currently, most of the text is spread across three lines.

**Comment by slysnivy** [comment]
Please look at the two most recent pull requests (v.0.2.6 v1 and v2) for a one line vs. three line version of the dsnclass.Text. Pull only one if you'd want to change the levels file, otherwise if you want it to be the same, reject both. For me, one line would be easier to work with (and more efficient). @shoc71

**Comment by shoc71** [comment]
I think the latest PR #120 you submitted, fixed this issue

**Comment by slysnivy** [comment]
Ok, sounds good :)

**Comment by shoc71** [comment]
Will keep this consistent in future PRs, if possible. If not, submit it as a PR request to fix the issue. I imagine this formatting issue is easily fixed on PyChram
