### ISSUE TITLE
Level difficulty and player speed

### ISSUE THREAD

**Issue by slysnivy** [shoc71/dont-stop-now#137]
I need to implement different speed settings for the player movement (but not game) depending on difficulty. This will likely mean keeping the FPS constant (120) but changing movement (ex: factor of 1/2). I can do this by multiplying the player physics by 3/2n, then have n represent the difficulty (something like Easy = 3, Normal = 2, Hard = 1) as an integer counter.

**Comment by slysnivy** [comment]
An easier way would use a dictionary with the difficulty settings (easy, normal, hard) to translate into their respective physic modifiers (0.6, 0.8, 1.0)

**Comment by shoc71** [comment]
Sounds like everything is good. I'm assuming right now based on the speed, the difficulty is now hard.

**Comment by slysnivy** [comment]
Yea, I'll implement it in the next patch

**Comment by slysnivy** [comment]
This feature has been added in dsn_class v.0.2.4 and dsn_levels v.0.3.1
