### ISSUE TITLE
More statistics to include

### ISSUE THREAD

**Issue by slysnivy** [shoc71/dont-stop-now#139]
Currently there's death and jump counters, what other stats should we include? One idea is total play time and time taken to beat the level.

**Comment by shoc71** [comment]
That's honestly a good idea!

**Comment by slysnivy** [comment]
Time taken and total time have been added in:
main v.0.2.0
dsn_levels v.0.3.0
dsn_class v.0.2.3
I will close this issue for now. Additional statistics desired should be requested with another separate issue/discussion post
