### ISSUE TITLE
Adding Skin and Meat to the levels

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#182]
Most of the levels of concepts and collision have been tested and tried and approved. They require adding skin or meat or (self.draw) over the object so that it looks like colored. 

This is an idea that I have, no clue if we should keep the game with the main 5 colors (black, white, red, cyan, green) or expand the colors scale and apply them to all levels.

**Comment by shoc71** [comment]
If that can be coded into the game like self.animate_player or self.animate_block with defined parameters of distance traveled and other things of the sort without affecting framerate of the gameplay and it's easy to define, I see no issues including it into the game. However, there are some levels that would require re-editing them again to include these, and always less is more. I made that mistake in candles and need to fix that there. @slysnivy what we could have is a solution animation for the player that they can click if they are confused.

**Comment by slysnivy** [comment]
@shoc71 The solution replay is a good idea but you can just code that in with a predetermined set of inputs using pygame.time.get_ticks() to indicate when to jump. 

1. For the animations I was talking about, I think we could implement a self.animate_block that would be cosmetic only (no collision) like self.draw. It would be defined by the rect object, type of movement (change x or y), and speed. The rects would then move back and forth (or "boomerang") using these parameters. Their position would be updated (x += 1 etc) in self.update(). This would result in smoother but less detailed dynamic art (within a reasonable amount of time) 

2. An easier self.animate_block would be to have no change in x or y, but have it change what rect it is (different x, y, width and height). If you draw something with multiple rects in self.animate_block, you can make choppy (ex: will change across 3 frames of art across 5 seconds) but, it will be more detailed.

**Comment by shoc71** [comment]
@slysnivy as mentioned before, if this can be coded in the game then I have no problem and I support this idea. What worries me is that the level animations might be distracting or it might create the illusion that the player is playing a new game entirely (we could have it as a secret level mode where this could be more the case), but we'll see.

**Comment by shoc71** [comment]
You also gave me an idea of including in the settings options of turning on animations for the game or not. Otherwise, it can all be self.draw

**Comment by slysnivy** [comment]
@shoc71 If it's distracting or would ruin the game, then let's not include it.

**Comment by shoc71** [comment]
No you gave me the perfect idea. Once we are done with the selections and confirmed everything else, this will be final touches to the game. All animations will be light
