### ISSUE TITLE
Hold Arrow_key to navigate through levels quicker

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#187]
dk, let's try fixing it that everytime you want to go to a certain you don't need to hit and wait everytime to get there

**Comment by slysnivy** [comment]
This was implemented in dsn_levels v.0.3.2+

**Comment by slysnivy** [comment]
I was also thinking when we get to 50+ levels, the amount of levels passed for 1 animation jump would increment by 10 instead. During this quicker jump the animation could completely be removed to give it the illusion of going quickly.

An alternative solution is to group many levels into one set that would be selected. This would make the levels seem larger and make selecting levels easier.

What are your thoughts? Feel free to disagree.
