### ISSUE TITLE
Make background more adjustable (in settings)

### ISSUE THREAD

**Issue by slysnivy** [shoc71/dont-stop-now#197]
Ex: background having 50 shades of grey. Using https://stackoverflow.com/questions/51973441/how-to-fade-from-one-colour-to-another-in-pygame#:~:text=Use%20set_alpha()%20to%20perform,Repeat%20as%20desired.

**Comment by shoc71** [comment]
As a slider

**Comment by slysnivy** [comment]
@shoc71 What colors would we like for the background? would WHITE to GREY be ok?

**Comment by shoc71** [comment]
that's what I was thinking as well. Maybe a good range would be
White (255, 255, 255) --> Light_Grey (200, 200, 200)

**Comment by slysnivy** [comment]
Also for now, I'll leave it to be controlled by A/D since the game only uses WASD/Arrow Keys. I'll still make a slider for it though just for looks 👍.

**Comment by slysnivy** [comment]
This was supposed to be closed with dsn_path_10 😅

**Comment by shoc71** [comment]
Yea that's weird but at least it's closed now
