### ISSUE TITLE
Adding New Unique Color for NightMode Gameplay

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#221]
color is Licorice but there are other shades or opacities of black, you can check some out [here](https://htmlcolorcodes.com/colors/shades-of-black/) but this is a unique color unlike the rest taking advantage of the gameplay. If this can be easily-coded like Orange or Blue, lemme know. If not, use this discussion to inform about which other shade of black you want for nightmode. I ask this for making the levels of nightmode soon.

Licorice = (52, 52, 52)

**Comment by shoc71** [comment]
I forgot to mention as soon as this issue is resolved/closed I will update all the relevant levels with this new addition in mind.

**Comment by slysnivy** [comment]
Would this would be the background for some levels, or would it be something to change in the settings? @shoc71

**Comment by shoc71** [comment]
No this would only affect certain blocks (self.draw only blocks) in the game when I assign them to be as is, when going through the levels for art/gameplay correction. @slysnivy

**Comment by slysnivy** [comment]
Would this be two versions of the same level? Or just changing the decor in some levels?

**Comment by shoc71** [comment]
changing the decor in some levels. Like in pirate_cove or that pirate level there are two black blocks for self.draw (one top-rigth and the other middle-row side-left) those two blocks are there to deceive the player

**Comment by slysnivy** [comment]
So it would just be like changing some self.draw blocks to be licorice and have it be different from black? What were you talking about nightmode and nightmode gameplay/levels?

**Comment by shoc71** [comment]
"changing some self.draw blocks to be licorice and have it be different from black" - @slysnivy. Yes, that's correct. Night-mode gameplay is more or less having some blocks of the game be deceiving. Most of the levels are being made with [this image/concept idea](https://github.com/shoc71/dont-stop-now/blob/main/dont%20stop%20now/assets/images/sketches/windows%20-%20nightmode.jpg) in mind.

**Comment by slysnivy** [comment]
Oh I see, then it would be as easy as adding orange or blue since it'll be just self.draw

**Comment by shoc71** [comment]
Exactly correct
