### ISSUE TITLE
Reduce the jump interval timing 

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#234]
Some levels have gotten harder to beaten and downright impossible. This is reference #230, where self.player.freeze and 180 <= pygame.time.get_ticks() - self.jump_timer: -- this is what I'm thinking should work

**Comment by slysnivy** [comment]
Yea, I'll put it to 150 first, if the jumping early bug persists we can increment it up to 180

**Comment by shoc71** [comment]
got it
