### ISSUE TITLE
Make MenuScene and LevelSelect more visually appealing

### ISSUE THREAD

**Issue by slysnivy** [shoc71/dont-stop-now#235]
For example, we can have a purple guy jump on the selected menu option. Again, I was thinking we should add more dynamic movements or just stationary decoration. I think stationary decoration is the best option just so it doesn't take attention away from the title itself. What we can do is make the title splash pop out more by putting like a border around it, or maybe remove some excess text

**Comment by shoc71** [comment]
interesting idea and we'll look into it

**Comment by slysnivy** [comment]
@shoc71 I think the T in the title of "Don't Stop Now" might still be thick.
