### ISSUE TITLE
Change titles for some music tracks to include underscores.

### ISSUE THREAD

**Issue by slysnivy** [shoc71/dont-stop-now#240]
Some music tracks are missing underscores, should we include underscores for proper etiquette (I'm sure it still works).

**Comment by shoc71** [comment]
i think its better if we just give them a proper name from now on and I will let you have that honor.

**Comment by slysnivy** [comment]
That would be the hardest part for implementing music 😭

**Comment by shoc71** [comment]
Changing the name for the music_tracks???

**Comment by shoc71** [comment]
like the name and stuff, no it's pretty easy, and also don't worry about it. I would be to call the beat out for what it feels like then whatever random boring name I gave it. All you have to do is clone a copy and just rename it to whatever you want and implement it into the code. I'll put out a patch fixing all that tomorrow, if not, at least address.

**Comment by slysnivy** [comment]
For now, I'll just add the underscores. Then when I get Music working again, I'll randomly go through each track and rename them while I'm testing the levels and stuff. It's challenging since it's time consuming with no shortcuts.
