### ISSUE TITLE
Update PatchNotes

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#242]
updates.txt needs a an update which is long since overdue.

**Comment by slysnivy** [comment]
For reference, the next updates.txt should be from PR #119

**Comment by slysnivy** [comment]
We have 4 pages of PR's, 25 per page, so about 100 to sift through 💀. We don't have to do it all in one go, but for every time we stop, just make sure to mention the **next PR that needs to work on**. For example, "the next PR that needs to be put into updates is #119"

**Comment by shoc71** [comment]
yea that makes sense and hopefully it doesn't take that long
