### ISSUE TITLE
Make Candles possible to beat

### ISSUE THREAD

**Issue by slysnivy** [shoc71/dont-stop-now#244]
I'm currently testing out the music and I saw that I couldn't beat candles on Medium and Hard. My suggestion is to either increase the length of the last platform (in circled red), or to make the goal higher (also in circled red) as seen below
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/a792e958-cf3c-4ff7-82b0-ba8b97a6af6e). 
Another solution is to just increase gravity (which I don't think you want).

The good news is that I've found a bug in the gravity where it wasn't consistent because I cancelled out the difficulty factor by dividing it, and then multiplying it (💀 oops). 
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/ed691cfc-aa89-4e54-a95e-063040013be4)

Even though I said there wouldn't be anymore changes to the physics, would it be ok if I changed this? (it would mean more consistency across the difficulties 👍)

**Comment by slysnivy** [comment]
@shoc71

**Comment by shoc71** [comment]
working on it and finished it. It will be in the new patch, ltr today
