### ISSUE TITLE
REsizable Window

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#250]
self.screen =  pygame.display.set_mode(((500), (500)),pygame.RESIZABLE) <--- this is the command line but 

- [ ] need to limit the minimum size of the game to (1080,576)
- [ ] setting page should be able to display the size of the window, if the user wants the adjustablility
- [x] world walls can easily extendable
- [x] There is some random fun that can be had making some creative decisions with the random world walls

**Comment by slysnivy** [comment]
I have a few questions and comments.
What are world walls and what do they do?

For the sizing we also need to scale the levels and player appropriately. We know from experimenting this week that the minimum size that we have is fine and it's possible to scale things up.

**Comment by shoc71** [comment]
> To make things easier, we can have preset dimensions for the window size too

That's a good idea.

**Comment by shoc71** [comment]
> I have a few questions and comments. What are world walls and what do they do?
> 
> For the sizing we also need to scale the levels and player appropriately. We know from experimenting this week that the minimum size that we have is fine and it's possible to scale things up.

world walls are like any walls except they keep the player from falling outside of the game.

- as for the sizing, I'm thinking we keep everything else the same, like the levels and all that, but we could have static art in the background over the world walls like achievements or random texts

**Comment by slysnivy** [comment]
> world walls are like any walls except they keep the player from falling outside of the game.
What would be the point of world walls? Are they just there to visually declare a border? Right now if the player goes outside of the game (past a y level), they'd die and respawn.

> * as for the sizing, I'm thinking we keep everything else the same, like the levels and all that, but we could have static art in the background over the world walls like achievements or random texts
I disagree with this direction. It would add a lot of clutter that could take away from the levels and would make resizing the screen pointless. I think resizing should be used to see the game more easily on a larger monitor/display. What this idea goes for is keeping the same size game even if the screen is resized.

**Comment by shoc71** [comment]
But I do agree with you on some level that some of the game difficulty gets taken away by setting the game to a new size and adjusting it based on its difficulty and slightly strecthing the levels to fit with that mode as well, I think we might have to stick with adjusting the game into different screen_modes or just leave it as 1080, 562 as it was before and never even tocuh it

**Comment by slysnivy** [comment]
I think you're misunderstanding my point. Resizing should be used to allow the player to **see** the game if they need to (for example, they have a **larger screen** and need to **scale up** the game). Resizing also includes **scaling the level and player proportionally to the screen size**. There is no change to the game and it's difficulty as the player would be experiencing the same collision and speed. That's why, there **wouldn't be any white/free space as the player/levels/scenes would be _scaled up_ as well**. Just think of the game right now, but a bit larger.

If you desire world walls, I can put those in dsn_editor as a preset, but **they'll also be scaled up** with the window sizing as well, just like any other platform.

**Comment by slysnivy** [comment]
If scaling up the game makes it easier, then we can alter the speed as well proportionally to where it would stay consistent.

**Comment by shoc71** [comment]
> That's why, there **wouldn't be any white/free space as the player/levels/scenes would be _scaled up_ as well**. Just think of the game right now, but a bit larger.

OHH, that makes a lot more sense. Thanks for clarifying. There is no need for world_walls in that case.

> If scaling up the game makes it easier, then we can scale the speed as well proportionally to where it would stay consistent.

if that's the case, then everything sounds good.
