### ISSUE TITLE
Cleaning the folder

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#26]
once it looks nice and tidy, this issue can be resolved

**Comment by shoc71** [comment]
@slysnivy  feel free to resolve this issue to your satisfaction when you think the folder looks good and ready

**Comment by slysnivy** [comment]
readme.md needs to be updated

**Comment by slysnivy** [comment]
or else we can delete it for now

**Comment by shoc71** [comment]
check out Update README.md #64 however this links up

**Comment by slysnivy** [comment]
I think it's good now 👍

**Comment by slysnivy** [comment]
I think it's good now 👍

**Comment by slysnivy** [comment]
I like the new README.md description
