### ISSUE TITLE
Player Rendering

### ISSUE THREAD

**Issue by slysnivy** [shoc71/dont-stop-now#260]
I forgot that we had to move the player render out of render_text. Should we render the player above the text? Or keep it above all level elements except for text (will be behind text, but ahead of everything else).

**Comment by shoc71** [comment]
I'm thinking everything is fine, the way it is now. The player > text > draw > blocks, in terms of priority and viewing of pixels on screen.

**Comment by slysnivy** [comment]
So you want players to be on top of text?

**Comment by shoc71** [comment]
Yes, that's fine.
