### ISSUE TITLE
Sometimes Crashing Game... 

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#264]
![image](https://github.com/shoc71/dont-stop-now/assets/129419169/be017887-bf68-4b1f-95c8-ea93666081fa)

After playing through some of the levels for a little while, sometimes the game crashes and creates this error code. Think it has to do with #263 of the recall mechanism of the nodes and replay tracking from the txt files.

**Comment by slysnivy** [comment]
The error has to do with using self.deaths (count for how many deaths) to determine linked list length. 

**Full Details Below**
The bug occurs only during level or scene transitions (only after completing a level or changing between testing and editing in the editor). During the transition, the length of linked list may not match with the count of self.deaths. Self.deaths is used to count the length of the linked list, which causes a mismatch (error in this case where the length of the linked list is less than self.deaths).

**The fix**
The solution is to not use self.death as an indicator of linked list length and use the already present class function self.check_len(). 

**Future bug catching**
I will also reserve the else statement for error purposes only (not crash the program but make some indication that something's wrong).
