### ISSUE TITLE
Game Collision Rework

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#266]
https://github.com/shoc71/dont-stop-now/assets/129419169/45db276b-da7f-4162-b375-406e75983684

- 

- [x] Hit the corners correctly and you can break through the wall collision (btw that wall thickness is 7, which usually is never a problem)
- [x] Sometimes bouncing of walls during a jump, kills the jump and just sends you in the other direction (this sometimes happens and sometimes it doesn't)
- [x] Once in a while, the block will detect a wall that's vertically about a horizontal wall and it just bounces of that making it look like it bounced of nothing.

**Comment by shoc71** [comment]
![Screenshot_081923_115329_PM](https://github.com/shoc71/dont-stop-now/assets/129419169/16dda439-3511-41e4-823f-eb48cd145f76)
![Screenshot_081923_115637_PM](https://github.com/shoc71/dont-stop-now/assets/129419169/c25fabe4-3309-4152-8dd8-a69d349dcff8)

for issues 2 and 3

**Comment by shoc71** [comment]
![image](https://github.com/shoc71/dont-stop-now/assets/129419169/f5d12823-a785-4858-9814-9c185d2983d2)

for isssue 1

**Comment by slysnivy** [comment]
Ok, I'll do a complete rework for collision. Don't worry, the change in physics should be negligible (likely a difference in 1-2 units).

**Comment by shoc71** [comment]
@slysnivy  lava pits for whatever reason causes this error continuous after bouncing off the wall and hitting the win_zone

**Comment by slysnivy** [comment]
What error? Please describe it

**Comment by shoc71** [comment]
self.head = self.head.next
AttributeError: 'NoneType' object has no attribute 'next' is the error code
![image](https://github.com/shoc71/dont-stop-now/assets/129419169/d98266c3-596a-4cc5-97ac-28ddd7d0b95b)

**Comment by shoc71** [comment]
> What error? Please describe it

hopefully the images above help with the error message for the code.

**Comment by slysnivy** [comment]
@shoc71 You are using an outdated version of DSN (dsn_class, and likely dsn_levels too) as the append method for the ReplayChain class no longer uses "count" as a parameter. Furthermore, it should return an error message in the terminal. See picture for reference:
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/16974a36-f91c-49ed-b44a-82ee998b140e)

**Comment by slysnivy** [comment]
@shoc71 There's a new change in physics with the updated collision. Player's will be able to catch the ledge easier, or be able to move over gaps if they're small enough. Here are some pictures:
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/d3819b26-325a-4b39-83ef-fd4038fc5d17)
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/63efd676-6ddc-4e9f-99ad-5fca90f56eb8)
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/22436926-a286-4ab5-810b-b78f2d415093)
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/24a5e7f1-a1c0-473a-9c59-a0d3cf4a9399)

**Comment by shoc71** [comment]
I think there's no need for any gravity/collision updates like the ones you mentioned above. (I'm going to assume all the pictures above are from block_maze_3)
- As for the first picture is an intentional gap for the player to get stuck in for the user to have fun with. 
- The second picture is made in mind to be intentionally hard and punished for not being accurate and hitting that corner is going to be devasting.
- the third picture is a ledge grab which is necessary. I think could be used as an intentional level up boost as there are not too many instances of the player going upwards in a limited a 1080x576 dimensions.
- The fourth picture is what the current gravity and collision is I believe.

**Comment by slysnivy** [comment]
All pictures are from the updated but not released collision logic. The differences are the result of the collision problems outlined in this issue being fixed. I'm asking this question to make some adjustments to the collision logic. 

So you would rather have only the behaviours seen in the 4th pic?

**Comment by slysnivy** [comment]
If needed, could I ask you to redesign this level with slight adjustments to make it like before?

**Comment by shoc71** [comment]
> So you would rather have only the behaviors seen in the 4th pic?

Yes, BUT comment out that collision logic for the time being. Depending on the beta tester, responses we might need to adjust the collision logic and level desgins entirely.

**Comment by slysnivy** [comment]
> Yes, BUT comment out that collision logic for the time being. Depending on the beta tester, responses we might need to adjust the collision logic and level desgins entirely. 

I cannot comment it out as this is the collision rework. Keep in mind that **these are the changes that fix the collision and the issues outlined here**. The resulting collision behaviour is a product of these changes. 
Don't worry, it's easily adjustable, so I'll try to get it as close as possible to the old behaviour (the ledge part).

**Comment by slysnivy** [comment]
More specifically, this is a change to how collision is detected and it's logic, not an add on to the old logic.

**Comment by shoc71** [comment]
> I cannot comment it out as this is the collision rework. Keep in mind that **these are the changes that fix the collision and the issues outlined here**. The resulting collision behaviour is a product of these changes. Don't worry, it's easily adjustable, so I'll try to get it as close as possible to the old behaviour (the ledge part).

Understandable, let's keep the old collision that we have for now, when the issue arises again, I'll re-open this issue. Until then, I believe this is resolved (I will try to recapture the instance of me getting stuck into that image/video like before).

**Comment by slysnivy** [comment]
I disagree in closing the issue now and keeping the old collision logic. 

The new collision just needs like 2 more lines in the if statements to not have the ledge catching occur.

**Comment by shoc71** [comment]
> The new collision just needs like 2 more lines in the if statements to not have the ledge catching occur.

Ok! I'll leave this issue up and let you decide when it needs to be complete and done!

**Comment by slysnivy** [comment]
> Understandable, let's keep the old collision that we have for now (as I believe you have fixed this with the new collision logic in #263 and #262 and #265)

This is false, no collision was changed, as these were for the Replays feature (and one of them as a mistake commit)

**Comment by shoc71** [comment]
> This is false, no collision was changed, as these were for the Replays feature (and one of them as a mistake commit)

Just re-checked all the PR's and yes, you're right - there was no change to collision and I am sorry about that.
