### ISSUE TITLE
Death Counter for all levels and individuals levels

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#27]
(probably need to make professional stat.s)

**Comment by slysnivy** [comment]
I'll see if I can fix the respawn counter and change it to a death counter

**Comment by shoc71** [comment]
interesting, thanks for taking this issue

**Comment by slysnivy** [comment]
The most recent dsn_levels file has the death counter now, do you want to code the rendering part? It should be in the area with the "todo" comment

**Comment by slysnivy** [comment]
How should we visualize it, I was thinking we do it at the end of the level or during the game's pause menu

**Comment by slysnivy** [comment]
I agree in having the max amount of screen space dedicated to the level. Hence, let's have it during the menu-scene and pause-scene. I'll add it after the next dsn_levels.py release

**Comment by slysnivy** [comment]
Sorry for the delay (one month 👎). I put this feature in the most recent PR's (dsn_levels v.0.2.9 mainly).

**Comment by slysnivy** [comment]
Though it's not present in the pause screen, but we can figure that out another time
