### ISSUE TITLE
Collision and Death/Win zones (NOT urgent)

### ISSUE THREAD

**Issue by slysnivy** [shoc71/dont-stop-now#276]
With the new change in collision, it may not be possible to collide with death or win zones **if they're placed on top of a wall/platform**. I found this while testing ribbons and will include more levels here that need to be worked on. 

<details><summary>Why does this happen now?</summary>
<p>

The reason it worked before is that the collision would allow the player to go inside the block before realizing that it should not be and pulls it out. The difference now is that the collision is now preventative. If the player is moving and in that moment, were to collide and go inside the block in the next frame, it would be placed adjacent/right up against the block instead and never go inside the block.

</p>
</details> 

In the image below, usually you would collide and die with the death zone, despite it being on top of a wall. Now that collision was made to be mostly exact (right up against each wall/platform), it'll rebound off of the wall. 
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/8ba0149d-5303-4efb-bff9-f5df45450bc3)

**Comment by slysnivy** [comment]
I'll list more levels below that need reworking

**Comment by slysnivy** [comment]
List of levels:
- Avoid the red (level 5) - win zone
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/2cd50945-a08e-4eed-a768-63009cdd2704)
- Mouse (level 7) - win zone
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/d92c671f-d2f6-4dc6-a2ff-024e77e3526c)
- Lava pits (level 13) - win zone
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/520a7d74-576d-4141-9108-6f0d8f61c3f7)
- Lava comb (level 14) - win zone
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/c0e6b189-8505-4692-b48d-fd917707525a)
- Block maze 5 (level 16) - win zone
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/e2b8a3d7-abae-4216-b571-3b4ed9426fb1)
- Split path (level 17) - top and bottom win zone
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/9cd522a1-6c97-4e89-b89d-acf6a4573979)
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/19dce39a-981e-4149-9952-15c3f18ddd4e)
- Hop Scotch (level 20) - win zone
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/c08000fe-f666-4b5c-ae3a-38cb4e121e01)
- Ash tray (level 21) - win zone
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/9adfeb2f-c025-4239-bb8e-ac199d057895)
- Staggers (level 30) - win zone
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/e148b3cc-7049-4b65-b6e9-0dd9b6423873)
- You're getting in my way (level 32) - win zone
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/bdef731a-4745-47e8-a921-da7511480f46)
- Caves (level 33) - win zone
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/1efd5a56-80c0-4ede-ad7c-a86db3b0985a)
- Block maze 1 (level 35) - win zone
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/458b0c43-8e9d-4a08-a9a3-e2784b9e96bc)
- Block maze 2 (level 36) - win zone
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/45d22c75-ebf0-41c1-9d8e-985d98fee5d2)
- Letters (level 41) - win zone
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/b5bb6fdc-f587-461e-aa71-5c657d1064a4)

Also, a good piece of info is that it took me about **50** minutes to beat all the levels so far. 👍

**Comment by shoc71** [comment]
@slysnivy I'll fix/adjust all the levels mentioned above in due time as I am making more levels and will update you on which ones have been reworked and completed.

**Comment by slysnivy** [comment]
Yea no rush. For the level win zones, you can just move the zone just so it sticks out of a wall a little (move x back by like 1 or 2).

**Comment by slysnivy** [comment]
I added some check boxes too so you can let me know when you've reworked a level 👍

**Comment by shoc71** [comment]
There are some extra levels that I did notice this issue on before (I didn't get all of them sadly). I managed to deal with most of the ones listed on this list. If there are any other levels worth mentioning about this issue, be sure to either re-open this issue or make a new one, as I will be closing this one shortly.

**Comment by slysnivy** [comment]
Sure and thanks! Just letting you know that the next collision update will make it so that this issue occurs every time instead of sometimes.

**Comment by slysnivy** [comment]
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/42a119dd-bfcd-4634-9bf5-927d9275e817)
[ ] Doors (Level 9) is unbeatable due to the player not dropping down, likely due to the new collision update.

**Comment by shoc71** [comment]
got it, this issue on that level will be resolved in the next update.

**Comment by shoc71** [comment]
I believe I checked all the levels and resolved it with #282, so I'm going to close it now.
