### ISSUE TITLE
Two X_factor levels. One's not working

### ISSUE THREAD

**Issue by slysnivy** [shoc71/dont-stop-now#277]
After resolving issue #276, the second duplicate X_factor level needs to be removed, as it's missing the self.win_zones:
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/7d10b8de-1671-46c7-991e-c4ea17f18329)

**Comment by shoc71** [comment]
I think that's just a copying error on my end, I'll resolve it easily within the next patch.
