### ISSUE TITLE
AutoClick Restart and Mute for Music

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#285]
sometimes during the gameplay its annyoing for new players to hit pause then restart. Some beta-testers have requested hitting restart almost immediately when they screw up. Also, something to adjsut the volume as well.

**Comment by slysnivy** [comment]
For the instant respawn how about we make it double tap R to respawn. I suggest double tap to avoid accidental presses causing the player to restart the level.

**Comment by shoc71** [comment]
I agree with the concept for now but let's keep it as a single tap 'r' for restarting levels. I thinking somehow in options, we are able to give players the option of choosing which one they prefer in the future.
