### ISSUE TITLE
Checkpoint Boxes Function needs to be made

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#29]
Save respawn point (in the same level), if hard/impossible levels

**Comment by slysnivy** [comment]
removed bug label as it's not implemented yet to be a bug

**Comment by slysnivy** [comment]
What color would the respawn boxes be?

**Comment by shoc71** [comment]
let's have them as light green

**Comment by slysnivy** [comment]
This feature has been added in dsn_levels v.0.2.0
