### ISSUE TITLE
The Second Great Split on levels.txt and File Reading

### ISSUE THREAD

**Issue by slysnivy** [shoc71/dont-stop-now#298]
The file reader (load_levels) needs to now be able to read **multiple** files (higher in scope) and **add onto** the existing level dictionaries instead of overwriting them. What needs to be done in dsn_class is:
- [x] Change load_levels to **add onto** level_set and level_elements
- [x] Add a new method in memory to **read a folder through a file path** and get **all the files** containing levels. Then have this method **call** load_levels
- [x] This would also be a good opportunity to put in error checks (try/except/else) into the file reader too

**Comment by shoc71** [comment]
What do you mean by the second great split? Are you exclusively referring to levels.txt as the second great split with the first great split being in the code being the three way split of class, main, and levels?

**Comment by slysnivy** [comment]
Yea, levels.txt is the second great split
