### ISSUE TITLE
Options Difficulty

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#299]
Trying to set the volume and the brightness of the game was both inconsistent and confusing even after reading the comments for the code. Think we should put a max and a min for the volume and there should be indicator of the extremes avaliable

- [x] + or - for the volume
- [x] the color white or grey on either side of the scale

**Comment by slysnivy** [comment]
I will add that in the next update

**Comment by slysnivy** [comment]
Actually, I'll add that in the update that will improve visuals overall for the menus
