### ISSUE TITLE
Square Block inside platform

### ISSUE THREAD

**Issue by slysnivy** [shoc71/dont-stop-now#58]
This maybe what's causing the square to get stuck on the platform going left and right, where the square block has sunken inside the block, likely due to gravity taking over and moving the square before the collision is detected. Expect the collision to be updated in the next patch.
![image](https://user-images.githubusercontent.com/47337807/244840517-ebb3dfa4-9573-46d4-8a26-4154aedb457d.png)

**Comment by shoc71** [comment]
funny bug we can't have in the game but it made for some great clips and funny collision logic

**Comment by shoc71** [comment]
https://github.com/shoc71/dont-stop-now/assets/129419169/cf368c96-66c7-4a3e-8368-8d3ba2685823

**Comment by slysnivy** [comment]
It's due to there being walls inside of the platform. There wasn't any top platform logic for walls, allowing the block to easily sink in

**Comment by slysnivy** [comment]
I noticed this only occurs from the left side of any platform

**Comment by shoc71** [comment]
yea this bug can be easily and closed and dealt with. I think you already solved this in your latest patch but just in case have for some of the levels readjusted the block size (level block maze 5) but you are fixed tutlvl3 so thanks for that.

**Comment by slysnivy** [comment]
With the new v.0.1.6 fix for both dsn_class and dsn_levels, this glitch should be fixed, or very rare. In the case that it occurs again, this issue would be opened again.
