### ISSUE TITLE
Title card needs to be added

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#71]
either imported as a fancy jpg or something else entirely - as per @slysnivy request

**Comment by shoc71** [comment]
only for the menuscreen

**Comment by slysnivy** [comment]
If we don't want to have a fancy jpg, we could make a single or multiple tiny levels inside of the words: DONT STOP NOW. Don't worry about having multiple square me's on the screen at once, as it works:
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/0d71db1f-e396-4dab-b1aa-0ee76c2e0775)

**Comment by slysnivy** [comment]
We should get this issue out of the way, since it's been more than a month. @shoc71 Any other ideas? Otherwise we could go for my previous idea.

**Comment by shoc71** [comment]
Everything seems goood. WIll add "fancy" title card today

**Comment by shoc71** [comment]
Added with the latest for images
