### ISSUE TITLE
Direction of player changing incorrectly when interacting with platforms roofs while jumping

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#86]
https://github.com/shoc71/dont-stop-now/assets/129419169/2b43a540-0751-45ec-90a0-418eb94702ec

https://github.com/shoc71/dont-stop-now/assets/129419169/1ec01f27-fc54-4ff1-b236-495638b012ba

**Comment by shoc71** [comment]
there are also moments where this happens in "letters" with the letter e middle tooth - more testing necessary

**Comment by shoc71** [comment]
I suspect the new changes being made to change the setting of the player vaule of 1 or -1 that could affect the velocity of this thing as before it was "self.right" or "self.left". Test from your side

**Comment by shoc71** [comment]
v.0.1.8 release for collision bug

**Comment by slysnivy** [comment]
The fix has been released in v.0.1.8 fix 3. The problem included not recording x positions and hitbox being too large, which allowed the change in left and right to occur at unexpected areas.
