### ISSUE TITLE
List for level-spawns and ratings for difficulty as my interpretation of it is messy

### ISSUE THREAD

**Issue by shoc71** [shoc71/dont-stop-now#88]
### List of levels and their spawn
**TutorialLevel1(12, 320, 1)** - Hallway - _needs more decorations_
**TutorialLevel2(12, 80, 1)** - Dropguide to Solution - _needs more decorations_
**TutorialLevel3(12, 297, 1)** - Jump Over the Box - _needs more decorations_
**TutorialLevel4(12, 200, 1)** - Mind the Gap - _move the text & more decorations_
**EasyLevel1(12, 292, 1)** - Candles - _maybe needs more decorations_
**EasyLevel2(132, 282, 1)** - Mouse - _I think it's good - would be nice if we had a sfx play if the player collides with the mouse nose_
**EasyLevel3(12, 12, 1)** - Block Maze 5 - _moved to another location or had as a failed level concept_
**EasyLevel4(37, 489, 1)** - Letters - _I think this is good - might more coloring with white blocks_
**EasyLevel5(30, 518, 1)** - Staggers - - [ ] _would be nice if I could add some blue and white and yellow boxes in the level to show so lights or something_
**EasyLevel6(21, 21, 1)** - Spiral - _made for testing purposes only. Needs more polish for it to be a playable level for the public._

**___--------_NEEDS MORE TESTING______**
**EasyLevel7(37, 527, 1)** - Burger - _needs more dull coloring to avoid confusion_
**EasyLevel8(21, 258, 1)** - Tip-toe - _boxes need readjustments and better positioning_
**EasyLevel9(37, 524, 1)** - You're not alone - _boxes need readjustments and better positioning, more decorations for people and "platforms"_
**EasyLevel10(48, 53, 1)** - Ritual or (keys) - _boxes need readjustments and better positioning, more text, and renamed to Hardlevel1 sonn..._
**EasyLevel11(32, 338, 1)** - Reverse Lamp - _I think this one is solid and good_
**EasyLevel12(37, 47, 1)** - Propaganda - _This is a hard one and needs more detailed block as well towards the bottom_
**EasyLevel13(23, 259, 1)** - Split Path - _this one is eh_
**EasyLevel14(69, 263, 1)** - Uneven platforms - _could use more decorations and movements for improvements_
**EasyLevel15(6, 272, 1)** - Lava drip - _lvl just needs more testing and adjusting_
**EasyLevel16(33, 44, 1)** - Ashtray - _we good here_

**EasyLevel17(37, 47, 1)** - ribbons - _we good_
**EasyLevel18(37, 47, 1)** - Choose Bait - _better decorations at the bottom_
**EasyLevel19(26, 62, 1)** - Upper Gates - _more jumping and decorations needed_
**EasyLevel20(48, 53, 1)** - na
**EasyLevel21(32, 338, 1)** - na
**EasyLevel22(37, 47, 1)** - na
**EasyLevel23(23, 259, 1)** - na
**EasyLevel24(69, 263, 1)** - na
**EasyLevel25(6, 272, 1)** - na
**EasyLevel26(33, 44, 1)** - na
**EasyLevel27(37, 527, 1)** - na
**EasyLevel28(21, 258, 1)** - na
**EasyLevel29(37, 524, 1)** - na
**EasyLevel30(48, 53, 1)** - na
**EasyLevel31(32, 338, 1)** - na
**EasyLevel32(37, 47, 1)** - na
**EasyLevel33(23, 259, 1)** - na
**EasyLevel34(69, 263, 1)** - na
**EasyLevel35(6, 272, 1)** - na
**EasyLevel36(33, 44, 1)** - na

____Unorgainzed levels
**TutorialLevel14(33, 44, 1)** - daz maze- _no known spawn, figure it out_
**TutorialLevel24(0, 300, 1)** - red floor- _we good here_
**TutorialLevel5(10, 100, 1)** - sandwich- _no known spawn, figure it out_
**TutorialLevel6(0, 140, 1)** - Not the same - _more blocks here needed _
**TutorialLevel7(0, 120, 1)** - Jump under the platform - _we good here_
**HardLevel1(33, 44, 1)** - Small Steps - _figoure spawn out and difficulty of level_

**Note to self and others who might read this.**
This issue shouldn't be resolved until all the levels have been tested and approved for functionality, difficulty, and decorations.
This list will be updated and modified when improvements are made with it.

**Comment by shoc71** [comment]
Levels are names are going to be renamed - easylevel16(33,44,1) --> Ashtray(33,44,1)

I think this is better and easier also for whatever reason there are walls |:( so yea

**Comment by slysnivy** [comment]
I think changing the name is fine, since we can still keep track of level order with level ID (or with their order in the text file). Also if it's a list for level names, I believe we should move it to the discussions section. For the walls, I've been thinking to completely remove, as platforms have the exact same collision. I will open up a separate issue for it and we should change levels.txt. 👍

**Comment by slysnivy** [comment]
If you want to, we can revert the changes I've made.

**Comment by shoc71** [comment]
nah its fine this way, I'll change it soon in the future
