### ISSUE TITLE
Rework on how the level is rendered

### ISSUE THREAD

**Issue by slysnivy** [shoc71/dont-stop-now#95]
Please note that new levels should be rendering as shown below:
![image](https://github.com/shoc71/dont-stop-now/assets/47337807/163217b2-7095-45cf-8252-972c9736cde0)

render_text is now last and after level text that uses screen.blit. Please make these changes in future levels (all levels have been updated to have this in v.0.2.0). :)

**Comment by shoc71** [comment]
checked all the levels and fixed this for future levels
